# Generated by Django 4.1.2 on 2022-10-23 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_author', to='blog.author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.ManyToManyField(blank=True, related_name='article_languages', to='blog.language'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='article_tags', to='blog.tags'),
        ),
    ]
